name: py37drn
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2019.8.28=0
  - certifi=2019.9.11=py37_0
  - cffi=1.12.3=py37h2e261b9_0
  - cloudpickle=1.2.2=py_0
  - cudatoolkit=10.0.130=0
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.0=py37h7b6447c_0
  - dask-core=2.5.0=py_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py37_1
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h9c2bf20_1
  - imageio=2.5.0=py37_0
  - intel-openmp=2019.4=243
  - joblib=0.13.2=py37_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py37he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - matplotlib=3.1.1=py37h5429711_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.14=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.3=py_0
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.17.2=py37haad9e8e_0
  - numpy-base=1.17.2=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1d=h7b6447c_2
  - pandas=0.25.1=py37he6710b0_0
  - pcre=8.43=he6710b0_0
  - pillow=6.1.0=py37h34e0f95_0
  - pip=19.2.3=py37_0
  - pycparser=2.19=py37_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - python=3.7.4=h265db76_1
  - python-dateutil=2.8.0=py37_0
  - pytorch=1.0.1=py3.7_cuda10.0.130_cudnn7.4.2_2
  - pytz=2019.2=py_0
  - pywavelets=1.0.3=py37hdd07704_1
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scikit-image=0.15.0=py37he6710b0_0
  - scikit-learn=0.21.3=py37hd81dba3_0
  - scipy=1.3.1=py37h7c811a0_0
  - setuptools=41.2.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - sqlite=3.30.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - torchvision=0.2.2=py_3
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - beautifulsoup4==4.8.0
    - chardet==3.0.4
    - click==7.0
    - cython==0.29.13
    - gtts==2.0.4
    - gtts-token==1.1.3
    - idna==2.8
    - imageio-ffmpeg==0.3.0
    - moviepy==1.0.1
    - msgpack-python==0.5.6
    - msgpack-rpc-python==0.4.1
    - opencv-python==4.1.1.26
    - pot==0.6.0
    - proglog==0.1.9
    - protobuf==3.10.0
    - python-xlib==0.25
    - pyuserinput==0.1.11
    - requests==2.22.0
    - soupsieve==1.9.4
    - tensorboardx==1.6
    - tornado==4.5.3
    - tqdm==4.36.1
    - transforms3d==0.3.1
    - urllib3==1.25.6
prefix: /home/clic/miniconda3/envs/py37drn

